### PR TITLE
Support `raw` as a output format

### PR DESCRIPTION
**Pull request by liquidz**
Feature like jq's `--raw-output` option.
https://stedolan.github.io/jq/manual/

### CODE REVIEW

**Comment by borkdude** [comment]
Hi @liquidz,

Can you give an example of when this is useful and why you need this?
Is this for stripping quotes from strings like in the last example of the following?

```
$ echo '{:a "foo"}' | jet --query :a
"foo"
$ echo '{:a "foo"}' | jet --query :a | bb '(println *in*)'
foo
```

Kind regards,

Michiel

**Comment by liquidz** [comment]
@borkdude 
I'd like to extract a value containing multiline strings from JSON.
Currently I'm using `jq` for it, but because `jq` query is complecated and our project is using Clojure,  `jet` query is suitable for us.
With this output option, I can switch to `jet` from `jq` easily.

> Is this for stripping quotes from strings like in the last example of the following?

Oh, I didn't notice the combination of `jet` and `bb`!
However using `bb` just for raw output seems redundant for me.

I'll close this PR if mere extraction is not a `jet` role.

**Comment by borkdude** [comment]
From jq's docs:

> With this option, if the filter’s result is a string then it will be written directly to standard output rather than being formatted as a JSON string with quotes. This can be useful for making jq filters talk to non-JSON-based systems.

Maybe it makes sense to have a separate `--raw-output` flag and only activate that when the output is really a string and not when it is a map, vector, etc?

**Comment by liquidz** [comment]
Sounds good :)
I close this PR.

**Comment by borkdude** [comment]
@liquidz Even shorter with bb:

```
$ bb -o '*in*' <<< "hello"
hello
```

**Pull request closed without merging**
