### PR TITLE
Make --interactive aware of stdin

### PR DESCRIPTION
**Pull request by reedho**

### CODE REVIEW

**Comment by borkdude** [comment]
@reedho Could you update your PR?

**Comment by reedho** [comment]
Done, please recheck.

**Comment by borkdude** [comment]
@reedho Could you also add a unit test in main-test.clj?

E.g. something like:

```
(deftest jeti-test
  (let [stdin *in*
        tty (clojure.java.io/writer "/dev/tty")]
    (binding [*in* tty]
      (with-in-str "Y\n"
        (binding [*in* stdin]
          (with-in-str "{:a 1}" (main/-main "--interactive")))))))
```

Note that the above code doesn't work, just a rough idea.

**Comment by borkdude** [comment]
@reedho The reason why I'm hesitant to merge this without a test is that I don't know what the `/dev/tty` trick exactly does and how it will behave on different platforms. Right now, this tool is tested with Mac, Linux and the JVM. JVM users can also use it on Windows right now. To be fair, I haven't written a test for jeti proper yet, so I think that would be a good start and then write a test for this PR.

**Comment by reedho** [comment]
Hold on, still figuring out the proper testing, at least i will try to make it be the same level with the existing tests.

**Comment by borkdude** [comment]
@reedho No hurry, just trying to explain my thinking :-).

**Comment by borkdude** [comment]
@reedho One way to go might be to pass the reader explicitly to `start-jeti` so we don't use `*in*` there at all. So `(defn start-jeti! [start-val reader] ...)`. That might make it easier to write a test for it?

**Comment by reedho** [comment]
My previous concern is to reuse input output processing logic in `-main` to feed as `start-val` for `start-jeti`, but i found that this break `--interactive` when no input (pipe) is given. 

At the moment i'm thinking to change parse `--interactive` option as string instead of bool. This will provide information to start-jeti without processing input, or process input first then feed. This will also ease testing, e.g.

`jet --interactive` start-jeti without processing input.

`echo 1 | jet --interactive stdin` start-jeti with start-val `1`, binding `*in*` to /dev/tty (reopen stdin behavior).

`echo 1 | jet --interactive ':jeti/exit'` start-jeti prompt with start-val `1`, binding `*in*` with string reader ":jeti/exit". Useful for testing.

How do you think?

**Comment by borkdude** [comment]
@reedho My preference would be to not complicate the use of stdin/*in* and to use the output of a process as an argument, so like:

```
output=$(...)
jet --interactive "{:init-val $output}"
```

or just:

```
output=$(...)
jet --interactive "{:init-val $(...)}"
```

Passing an options map to `--interactive` instead of positional arguments keeps it more flexible for the future. We can assume that `:init-val` is EDN. If people want to convert from another format they just invoke `jet --from json` one time before.

**Comment by borkdude** [comment]
Awesome, thank you.

**Pull request merged**
