### PR TITLE
Added -C for --collect

### PR DESCRIPTION
**Pull request by dotemacs**
Since `-c` is potentially going to be used for `--colorise` option, I
figure that `-C` might be good, shorter alternative to `--collect`.

If you don't like `-C`, please feel free to suggest another alternative.
Thanks

### CODE REVIEW

**Comment by borkdude** [comment]
@dotemacs Do we absolutely have to add a short option for every long option? The `--collect` option isn't used that frequently I think, or do you think otherwise?

**Comment by dotemacs** [comment]
> @dotemacs Do we absolutely have to add a short option for every long option? The `--collect` option isn't used that frequently I think, or do you think otherwise?

We don't have to do anything. 

I just think that it would be nice to have short switches because the long ones are a GNU-ism and arguably quicker to type on the command line.

I think that `jet` is a super cool tool and deserves a wider audience/user base, potentially as an alternative to `jq`. And having the short switches could potentially contribute to usage.

My main motivation for adding `-C` is that I re-read the README again and saw this example:

```
$ echo '{"a": 1} {"a": 1}' | jet --from json --keywordize --collect --to edn
[{:a 1} {:a 1}]
```

And figured that I'd prefer to type it in as:

```
$ echo '{"a": 1} {"a": 1}' | jet -i json -k -C
[{:a 1} {:a 1}]
```

But this is your project, you can decide what goes in.

**Comment by borkdude** [comment]
OK, merged ;)

**Comment by borkdude** [comment]
@dotemacs In hindsight, let's just make `--collect` `-c` and we can use `-C` for colorize in the future (didn't think about this). Would you like to put another PR for this?

**Comment by dotemacs** [comment]
> @dotemacs In hindsight, let's just make `--collect` `-c` and we can use `-C` for colorize in the future (didn't think about this). Would you like to put another PR for this?

On it!

**Pull request merged**
