### PR TITLE
Csv support

### LINKED ISSUE #52: Add CSV input/output
CSV is still a very common format, and it would be great to be able to easily feed a CSV file into `bb` for instance.

Unfortunately it's not terribly well standardized when it comes to quoting, and line and cell separators, and there might have to be some detection of a Byte Order Mark at the start.

`clojure/data.csv` would be the obvious choice, using its defaults for a `csv` format, and maybe also adding a `tsv` format with commas instead of tabs.

### PR DESCRIPTION
**Pull request by plexus**
Follow-up to #53, closes #52.

Now with an extra `--csv`

### CODE REVIEW

**Comment by plexus** [comment]
Added a README stanza.

**Comment by borkdude** [comment]
@plexus 

In this comment:
https://github.com/borkdude/jet/pull/53#issuecomment-552410550

I intended to communicate that adding CSV to babashka is probably a better fit than jet, considering all the options and questions that it raises. So I recommend people using that instead for CSV.

**Comment by plexus** [comment]
Fair enough, I think having an easy way to do CSV <-> EDN conversion would be quite useful, but I don't have a horse in this race.

**Comment by borkdude** [comment]
@plexus One easy way would be quite useful, but code offers more flexility which seems to be needed to support CSV edge cases.

Remaining questions from #53:

- I expect `cat foo.csv | jet --from csv` to output: `[ row1, row2 ]` instead of `row1, row2`. Why does your PR do it the other way, what practical use case does it have?
- Some people would want to have `[{:row-1-header1 ..., :row-2-header2 ...}]` instead.

People can make theses choices in babashka now for themselves without us having to support command line options.

I might re-consider in the future.

**Comment by borkdude** [comment]
@plexus I changed the base to the `csv-support` branch to which I'm willing to merge, for future reference, but the tests aren't passing.

**Pull request merged**
